In [82]:
# Import libraries
import talib as ta
from talib import abstract
import pandas as pd

In [83]:
# Read in data from csv
df = pd.read_csv('../Data/ETF_top_8_data.csv', header=[0, 1], parse_dates=True, index_col=[0])

In [84]:
# All availible functions within TA-Lib
ta.get_function_groups()

{'Cycle Indicators': ['HT_DCPERIOD',
  'HT_DCPHASE',
  'HT_PHASOR',
  'HT_SINE',
  'HT_TRENDMODE'],
 'Math Operators': ['ADD',
  'DIV',
  'MAX',
  'MAXINDEX',
  'MIN',
  'MININDEX',
  'MINMAX',
  'MINMAXINDEX',
  'MULT',
  'SUB',
  'SUM'],
 'Math Transform': ['ACOS',
  'ASIN',
  'ATAN',
  'CEIL',
  'COS',
  'COSH',
  'EXP',
  'FLOOR',
  'LN',
  'LOG10',
  'SIN',
  'SINH',
  'SQRT',
  'TAN',
  'TANH'],
 'Momentum Indicators': ['ADX',
  'ADXR',
  'APO',
  'AROON',
  'AROONOSC',
  'BOP',
  'CCI',
  'CMO',
  'DX',
  'MACD',
  'MACDEXT',
  'MACDFIX',
  'MFI',
  'MINUS_DI',
  'MINUS_DM',
  'MOM',
  'PLUS_DI',
  'PLUS_DM',
  'PPO',
  'ROC',
  'ROCP',
  'ROCR',
  'ROCR100',
  'RSI',
  'STOCH',
  'STOCHF',
  'STOCHRSI',
  'TRIX',
  'ULTOSC',
  'WILLR'],
 'Overlap Studies': ['BBANDS',
  'DEMA',
  'EMA',
  'HT_TRENDLINE',
  'KAMA',
  'MA',
  'MAMA',
  'MAVP',
  'MIDPOINT',
  'MIDPRICE',
  'SAR',
  'SAREXT',
  'SMA',
  'T3',
  'TEMA',
  'TRIMA',
  'WMA'],
 'Pattern Recognition': ['CDL2CROWS',
  'CDL3BLACKCROWS',
  'CDL3INSIDE',
  'CDL3LINESTRIKE',
  'CDL3OUTSIDE',
  'CDL3STARSINSOUTH',
  'CDL3WHITESOLDIERS',
  'CDLABANDONEDBABY',
  'CDLADVANCEBLOCK',
  'CDLBELTHOLD',
  'CDLBREAKAWAY',
  'CDLCLOSINGMARUBOZU',
  'CDLCONCEALBABYSWALL',
  'CDLCOUNTERATTACK',
  'CDLDARKCLOUDCOVER',
  'CDLDOJI',
  'CDLDOJISTAR',
  'CDLDRAGONFLYDOJI',
  'CDLENGULFING',
  'CDLEVENINGDOJISTAR',
  'CDLEVENINGSTAR',
  'CDLGAPSIDESIDEWHITE',
  'CDLGRAVESTONEDOJI',
  'CDLHAMMER',
  'CDLHANGINGMAN',
  'CDLHARAMI',
  'CDLHARAMICROSS',
  'CDLHIGHWAVE',
  'CDLHIKKAKE',
  'CDLHIKKAKEMOD',
  'CDLHOMINGPIGEON',
  'CDLIDENTICAL3CROWS',
  'CDLINNECK',
  'CDLINVERTEDHAMMER',
  'CDLKICKING',
  'CDLKICKINGBYLENGTH',
  'CDLLADDERBOTTOM',
  'CDLLONGLEGGEDDOJI',
  'CDLLONGLINE',
  'CDLMARUBOZU',
  'CDLMATCHINGLOW',
  'CDLMATHOLD',
  'CDLMORNINGDOJISTAR',
  'CDLMORNINGSTAR',
  'CDLONNECK',
  'CDLPIERCING',
  'CDLRICKSHAWMAN',
  'CDLRISEFALL3METHODS',
  'CDLSEPARATINGLINES',
  'CDLSHOOTINGSTAR',
  'CDLSHORTLINE',
  'CDLSPINNINGTOP',
  'CDLSTALLEDPATTERN',
  'CDLSTICKSANDWICH',
  'CDLTAKURI',
  'CDLTASUKIGAP',
  'CDLTHRUSTING',
  'CDLTRISTAR',
  'CDLUNIQUE3RIVER',
  'CDLUPSIDEGAP2CROWS',
  'CDLXSIDEGAP3METHODS'],
 'Price Transform': ['AVGPRICE', 'MEDPRICE', 'TYPPRICE', 'WCLPRICE'],
 'Statistic Functions': ['BETA',
  'CORREL',
  'LINEARREG',
  'LINEARREG_ANGLE',
  'LINEARREG_INTERCEPT',
  'LINEARREG_SLOPE',
  'STDDEV',
  'TSF',
  'VAR'],
 'Volatility Indicators': ['ATR', 'NATR', 'TRANGE'],
 'Volume Indicators': ['AD', 'ADOSC', 'OBV']}

In [98]:
def bbands_create_df(timeperiod, nbdevup, nbdevdn, ticker):
    data=df[ticker]['close']
    bbands_abstract = ta.BBANDS(data, 20, 2, 2)
    BB_df = pd.DataFrame(bbands_abstract).transpose()
    BB_df.rename(columns={0:'BB_UPPER', 1:'BB_MIDDLE', 2:'BB_LOWER'}, inplace=True)
    return BB_df

In [99]:
ticker_list = list(dict.fromkeys((df.droplevel(axis=1, level=[-1]))))

In [100]:
bbands_df = pd.DataFrame()
for x in ticker_list:
    bbands = bbands_create_df(timeperiod=20, nbdevup=5, nbdevdn=5, ticker=x)
    df_temp = pd.concat({f"{x}": bbands}, axis=1)
    for BB in bbands.columns:    
        df[f'{x}', f'{BB}'] = bbands[BB]
df = df.sort_index(axis=1)

In [101]:
df

                  GDX                                                       \
             BB_LOWER BB_MIDDLE   BB_UPPER      close dividends       high
Date
2017-07-06        NaN       NaN        NaN  20.587141       0.0  20.788319
2017-07-07        NaN       NaN        NaN  20.318905       0.0  20.520083
2017-07-10        NaN       NaN        NaN  20.606304       0.0  20.740422
2017-07-11        NaN       NaN        NaN  20.730841       0.0  20.826640
2017-07-12        NaN       NaN        NaN  20.826639       0.0  21.133195
...               ...       ...        ...        ...       ...        ...
2022-06-28  28.334867   30.9670  33.599133  28.870001       0.0  29.780001
2022-06-29  27.977506   30.8025  33.627495  28.440001       0.0  29.270000
2022-06-30  27.436516   30.5725  33.708484  27.379999       0.0  28.400000
2022-07-01  27.282131   30.3130  33.343869  28.160000       0.0  28.370001
2022-07-05  26.853175   30.0330  33.212825  26.959999       0.0  27.930000

                                                         ...         XLV  \
                  low       open stock splits    volume  ...    BB_LOWER
Date                                                     ...
2017-07-06  20.539242  20.769159            0  37409500  ...         NaN
2017-07-07  20.117728  20.453024            0  57304600  ...         NaN
2017-07-10  20.108150  20.146471            0  52988200  ...         NaN
2017-07-11  20.366806  20.615883            0  35247100  ...         NaN
2017-07-12  20.788321  21.018237            0  39815200  ...         NaN
...               ...        ...          ...       ...  ...         ...
2022-06-28  28.820000  29.719999            0  18484000  ...  117.996049
2022-06-29  28.180000  29.160000            0  17375400  ...  118.142244
2022-06-30  27.330000  28.230000            0  24080100  ...  118.179901
2022-07-01  26.830000  26.959999            0  30974500  ...  118.246355
2022-07-05  26.459999  27.680000            0  28993000  ...  118.257144

                                                                      \
             BB_MIDDLE    BB_UPPER       close dividends        high
Date
2017-07-06         NaN         NaN   72.381187       0.0   73.152571
2017-07-07         NaN         NaN   72.748520       0.0   72.831164
2017-07-10         NaN         NaN   72.610756       0.0   72.803600
2017-07-11         NaN         NaN   72.528130       0.0   72.720974
2017-07-12         NaN         NaN   73.024017       0.0   73.262780
...                ...         ...         ...       ...         ...
2022-06-28  126.264444  134.532838  127.419998       0.0  130.589996
2022-06-29  126.107238  134.072231  128.529999       0.0  129.169998
2022-06-30  126.030132  133.880363  128.240005       0.0  128.970001
2022-07-01  125.973742  133.701130  129.679993       0.0  129.850006
2022-07-05  125.956529  133.655914  128.929993       0.0  128.960007


                   low        open stock splits    volume
Date
2017-07-06   72.280173   73.014824            0   6367700
2017-07-07   72.454661   72.638320            0   4371400
2017-07-10   72.427097   72.776052            0   3580000
2017-07-11   72.160804   72.564856            0   4117500
2017-07-12   72.867906   72.886276            0   8808200
...                ...         ...          ...       ...
2022-06-28  127.180000  129.940002            0   7518700
2022-06-29  127.389999  127.589996            0   9157700
2022-06-30  126.889999  127.860001            0  10697600
2022-07-01  126.860001  128.289993            0   9366600
2022-07-05  126.169998  128.429993            0   9984900

[1258 rows x 80 columns]